app = 'erode'
primary_region = 'arn'

[build]
dockerfile = 'Dockerfile.web'

[http_service]
internal_port = 4321
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0

[[vm]]
memory_mb = 256
cpu_kind = 'shared'
cpus = 1
